config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "articles#index"
  devise_for :admins
  resources :categories
  resources :articles
  resources :classrooms
  resources :students
end

app/models/classroom.rb
class Classroom < ApplicationRecord
  belongs_to :students
end

app/controllers/classrooms_controller.rb
class ClassroomsController < ApplicationController
  before_action :set_classroom, only: %i[ show edit update destroy ]

  # GET /classrooms or /classrooms.json
  def index
    @classrooms = Classroom.all
  end

  # GET /classrooms/1 or /classrooms/1.json
  def show
  end

  # GET /classrooms/new
  def new
    @classroom = Classroom.new
  end

  # GET /classrooms/1/edit
  def edit
  end

  # POST /classrooms or /classrooms.json
  def create
    @classroom = Classroom.new(classroom_params)

    respond_to do |format|
      if @classroom.save
        format.html { redirect_to classroom_url(@classroom), notice: "Classroom was successfully created." }
        format.json { render :show, status: :created, location: @classroom }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @classroom.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /classrooms/1 or /classrooms/1.json
  def update
    respond_to do |format|
      if @classroom.update(classroom_params)
        format.html { redirect_to classroom_url(@classroom), notice: "Classroom was successfully updated." }
        format.json { render :show, status: :ok, location: @classroom }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @classroom.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /classrooms/1 or /classrooms/1.json
  def destroy
    @classroom.destroy

    respond_to do |format|
      format.html { redirect_to classrooms_url, notice: "Classroom was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_classroom
      @classroom = Classroom.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def classroom_params
      params.require(:classroom).permit(:date, :students_id)
    end
end

app/helpers/classrooms_helper.rb
module ClassroomsHelper
end

app/views/classrooms/_classroom.html.erb
<div id="<%= dom_id classroom %>">
  <p>
    <strong>Date:</strong>
    <%= classroom.date %>
  </p>

  <p>
    <strong>Students:</strong>
    <%= classroom.students_id %>
  </p>

</div>

app/views/classrooms/_form.html.erb
<%= form_with(model: classroom) do |form| %>
  <% if classroom.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(classroom.errors.count, "error") %> prohibited this classroom from being saved:</h2>

      <ul>
        <% classroom.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :date, style: "display: block" %>
    <%= form.date_field :date %>
  </div>

  <div>
    <%= form.label :students_id, style: "display: block" %>
    <%= form.text_field :students_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/classrooms/edit.html.erb
<h1>Editing classroom</h1>

<%= render "form", classroom: @classroom %>

<br>

<div>
  <%= link_to "Show this classroom", @classroom %> |
  <%= link_to "Back to classrooms", classrooms_path %>
</div>

app/views/classrooms/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Classrooms</h1>

<div id="classrooms">
  <% @classrooms.each do |classroom| %>
    <%= render classroom %>
    <p>
      <%= link_to "Show this classroom", classroom %>
    </p>
  <% end %>
</div>

<%= link_to "New classroom", new_classroom_path %>

app/views/classrooms/new.html.erb
<h1>New classroom</h1>

<%= render "form", classroom: @classroom %>

<br>

<div>
  <%= link_to "Back to classrooms", classrooms_path %>
</div>

app/views/classrooms/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @classroom %>

<div>
  <%= link_to "Edit this classroom", edit_classroom_path(@classroom) %> |
  <%= link_to "Back to classrooms", classrooms_path %>

  <%= button_to "Destroy this classroom", @classroom, method: :delete %>
</div>